export const TODO_GET_TODOS_ACTION = "TODO_GET_TODOS_ACTION";
export const TODO_DELETE_TODO_ACTION = "TODO_GET_DELETE_TODO_ACTION";
export const TODO_UPDATE_TODO_ACTION = "TODO_UPDATE_TODO_ACTION";
export const TODO_UPDATE_STATUS_TODO_ACTION = "TODO_UPDATE_STATUS_TODO_ACTION";
export const TODO_GET_TODOS_BY_KEY_ACTION = "TODO_GET_TODOS_BY_KEY_ACTION";
export const TODO_ADD_TODO_ACTION = "TODO_ADD_TODO_ACTION";
export const TODO_GET_TODO_BY_ID_ACTION = "TODO_GET_TODO_BY_ID_ACTION";
//MUATATION
export const TODO_SET_TODOS_MUTATION = "TODO_SET_TODOS_MUTATION";
export const TODO_SET_TODO_MUATION = "TODO_SET_TODO_MUATION";
//GETTER
export const TODO_GET_TODOS_GETTER = "TODO_GET_TODOS_GETTER";
export const TODO_GET_TODO_GETTER = "TODO_GET_TODO_GETTER";

//Common module

//GETTER
export const COMMON_GET_LOADING_GETTER = "COMMON_GET_LOADING_GETTER";
export const COMMON_GET_AUTHEN_GETTER = "COMMON_GET_AUTHEN_GETTER";
//MUTAION
export const COMMON_SET_LOADING_STATUS_MUTATION =
  "COMMON_SET_LOADING_STATUS_MUTATION";
export const COMMON_SET_AUTHEN_MUTATION = "COMMON_SET_AUTHEN_MUTATION";
//COMON
export const ROLE = "role";
export const ROLES = {
  USER: "user",
  ADMIN: "admin"
};
